default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: admin
  password: lol12345
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test